<div style=" background-color: RGB(0,114,200);" >
<h1 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">PROJET 4 DATA ANALYST</h1>
<h2 style="margin: auto; padding: 20px 0; color:#fff; text-align: center">Réalisez une étude de santé publique avec R ou Python
</h2>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner codes, textes et graphique.

Cet outil est formidable pour plusieurs raisons:

+ il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'un instruction, de la corriger si nécessaire.
+ De rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ d'agrémenter de graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandée.

Et garder à l'esprit, qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

Note jeremy 
Est ce qu'il faut faire le calcul de la sous nutrition sur les pays qu'on a ? 
Est ce qu'il faut faire des graphiques ?
Rajouter le soja
La liste des céréales est difficile a trouver ...

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.1 - Importation des librairies</h3>
</div>

In [2]:
#Importation de la librairie Pandas
import pandas as pd

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">1.2 - Chargement des fichiers Excel</h3>
</div>

In [3]:
#Importation du fichier population.csv
population = pd.read_csv('DAN-P4-FAO/population.csv')

#Importation du fichier dispo_alimentaire.csv
dispo_alimentaire = pd.read_csv('DAN-P4-FAO/dispo_alimentaire.csv')


#Importation du fichier aide_alimentaire.csv
aide_alimentaire = pd.read_csv('DAN-P4-FAO/aide_alimentaire.csv')


#Importation du fichier sous_nutrition.csv
sous_nutrition = pd.read_csv('DAN-P4-FAO/sous_nutrition.csv')

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.1 - Analyse exploratoire du fichier population</h3>
</div>

In [6]:
#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(population.shape[0]))
print("Le tableau comporte {} colonne(s)".format(population.shape[1]))

Le tableau comporte 1416 observation(s) ou article(s)
Le tableau comporte 3 colonne(s)

In [6]:
#Consulter le nombre de colonnes
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes

In [7]:
#Affichage les 5 premières lignes de la table with Pandas
population.head()

          Zone  Année     Valeur
0  Afghanistan   2013  32269.589
1  Afghanistan   2014  33370.794
2  Afghanistan   2015  34413.603
3  Afghanistan   2016  35383.032
4  Afghanistan   2017  36296.113

In [8]:
#Nous allons harmoniser les unités. Pour cela, nous avons décidé de multiplier la population par 1000
#Multiplication de la colonne valeur par 1000
population['Valeur']=population.Valeur.multiply(1000)

In [12]:
#changement du nom de la colonne Valeur par Population
population = population.rename(columns={'Valeur': 'Population'})

In [13]:
#Affichage les 5 premières lignes de la table pour voir les modifications
#population.head()
display(population)

             Zone  Année  Population
0     Afghanistan   2013  32269589.0
1     Afghanistan   2014  33370794.0
2     Afghanistan   2015  34413603.0
3     Afghanistan   2016  35383032.0
4     Afghanistan   2017  36296113.0
...           ...    ...         ...
1411     Zimbabwe   2014  13586707.0
1412     Zimbabwe   2015  13814629.0
1413     Zimbabwe   2016  14030331.0
1414     Zimbabwe   2017  14236595.0
1415     Zimbabwe   2018  14438802.0

[1416 rows x 3 columns]

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.2 - Analyse exploratoire du fichier disponibilité alimentaire</h3>
</div>

In [14]:
#Afficher les dimensions du dataset
dispo_alimentaire.shape

(15605, 18)

In [27]:
#Consulter le nombre de colonnes
display(str(dispo_alimentaire.shape[1])+ " colonnes")
dispo_alimentaire.dtypes

'18 colonnes'

Zone                                                                 str
Produit                                                              str
Origine                                                              str
Aliments pour animaux                                            float64
Autres Utilisations                                              float64
Disponibilité alimentaire (Kcal/personne/jour)                   float64
Disponibilité alimentaire en quantité (kg/personne/an)           float64
Disponibilité de matière grasse en quantité (g/personne/jour)    float64
Disponibilité de protéines en quantité (g/personne/jour)         float64
Disponibilité intérieure                                         float64
Exportations - Quantité                                          float64
Importations - Quantité                                          float64
Nourriture                                                       float64
Pertes                                                           float64
Production                                                       float64
Semences                                                         float64
Traitement                                                       float64
Variation de stock                                               float64
dtype: object

In [30]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head(5)

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,NaN,NaN,5.0,1.72,0.20,0.77,53.0,0.0,NaN,53.0,NaN,53.0,NaN,NaN,NaN
1,Afghanistan,"Agrumes, Autres",vegetale,NaN,NaN,1.0,1.29,0.01,0.02,41.0,2.0,40.0,39.0,2.0,3.0,NaN,NaN,NaN
2,Afghanistan,Aliments pour enfants,vegetale,NaN,NaN,1.0,0.06,0.01,0.03,2.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,Ananas,vegetale,NaN,NaN,0.0,0.00,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,Bananes,vegetale,NaN,NaN,4.0,2.70,0.02,0.05,82.0,0.0,82.0,82.0,NaN,NaN,NaN,NaN,NaN

In [85]:
#remplacement des NaN dans le dataset par des 0

#Utilisation d'un masque pour 1 colonne / serie
serie1 = dispo_alimentaire["Exportations - Quantité"]
#serie1
#serie1.isna()
mask1 = serie1.isna()
dispo_alimentaire.loc[mask1, "Exportations - Quantité"] = 0
dispo_alimentaire.head()


#utilsation de fillna pour l'entièreté
dispo_alimentaire = dispo_alimentaire.fillna(0)

In [79]:
#Test de groupby mean()
dispo_alimentaire.groupby(['Zone', 'Produit'])['Disponibilité alimentaire en quantité (kg/personne/an)'].sum()

Zone          Produit
Afghanistan   Abats Comestible         1.72
              Agrumes, Autres          1.29
              Aliments pour enfants    0.06
              Ananas                   0.00
              Bananes                  2.70
                                       ...
Îles Salomon  Viande de Suides         4.70
              Viande de Volailles      3.34
              Viande, Autre            0.06
              Vin                      0.07
              Épices, Autres           0.48
Name: Disponibilité alimentaire en quantité (kg/personne/an), Length: 15605, dtype: float64

In [80]:
#Nombres de zones
display(dispo_alimentaire['Zone'].unique().size)

174

In [ ]:
#multiplication de toutes les lignes contenant des milliers de tonnes en Kg

#noms des colonnes 
col_Ktonnes = list(dispo_alimentaire.columns[3:5])
col_Ktonnes += list(dispo_alimentaire.columns[9:18])
display(col_Ktonnes)
len(col_Ktonnes)

#filtre sur ces colonnes

#Run Once
dispo_alimentaire[col_Ktonnes] *= 1000

#Check
#dispo_alimentaire[col_Ktonnes]

['Aliments pour animaux',
 'Autres Utilisations',
 'Disponibilité intérieure',
 'Exportations - Quantité',
 'Importations - Quantité',
 'Nourriture',
 'Pertes',
 'Production',
 'Semences',
 'Traitement',
 'Variation de stock']

,Aliments pour animaux,Autres Utilisations,Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,0.0,0.0,53000.0,0.0,0.0,53000.0,0.0,53000.0,0.0,0.0,0.0
1,0.0,0.0,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0
2,0.0,0.0,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
15600,0.0,0.0,3000.0,0.0,0.0,3000.0,0.0,2000.0,0.0,0.0,0.0
15601,0.0,0.0,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
15602,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15604,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
#Affichage les 5 premières lignes de la table
dispo_alimentaire.head()

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,Abats Comestible,animale,0.0,0.0,5.0,1.72,0.20,0.77,53000.0,0.0,0.0,53000.0,0.0,53000.0,0.0,0.0,0.0
1,Afghanistan,"Agrumes, Autres",vegetale,0.0,0.0,1.0,1.29,0.01,0.02,41000.0,2000.0,40000.0,39000.0,2000.0,3000.0,0.0,0.0,0.0
2,Afghanistan,Aliments pour enfants,vegetale,0.0,0.0,1.0,0.06,0.01,0.03,2000.0,0.0,2000.0,2000.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,Ananas,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,Bananes,vegetale,0.0,0.0,4.0,2.70,0.02,0.05,82000.0,0.0,82000.0,82000.0,0.0,0.0,0.0,0.0,0.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier aide alimentaire</h3>
</div>

In [92]:
#Afficher les dimensions du dataset
aide_alimentaire.shape

(1475, 4)

In [94]:
#Consulter le nombre de colonnes
aide_alimentaire.shape[1]

4

In [95]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

  Pays bénéficiaire  Année              Produit  Valeur
0       Afghanistan   2013  Autres non-céréales     682
1       Afghanistan   2014  Autres non-céréales     335
2       Afghanistan   2013         Blé et Farin   39224
3       Afghanistan   2014         Blé et Farin   15160
4       Afghanistan   2013             Céréales   40504

In [98]:
#changement du nom de la colonne Pays bénéficiaire par Zone
aide_alimentaire.rename(columns={"Pays bénéficiaire": "Zone"})

             Zone  Année                   Produit    Valeur
0     Afghanistan   2013       Autres non-céréales    682000
1     Afghanistan   2014       Autres non-céréales    335000
2     Afghanistan   2013              Blé et Farin  39224000
3     Afghanistan   2014              Blé et Farin  15160000
4     Afghanistan   2013                  Céréales  40504000
...           ...    ...                       ...       ...
1470     Zimbabwe   2015  Mélanges et préparations     96000
1471     Zimbabwe   2013              Non-céréales   5022000
1472     Zimbabwe   2014              Non-céréales   2310000
1473     Zimbabwe   2015              Non-céréales    306000
1474     Zimbabwe   2013                Riz, total     64000

[1475 rows x 4 columns]

In [97]:
#Multiplication de la colonne Aide_alimentaire qui contient des tonnes par 1000 pour avoir des kg
aide_alimentaire["Valeur"] *= 1000

In [99]:
#Affichage les 5 premières lignes de la table
aide_alimentaire.head()

  Pays bénéficiaire  Année              Produit    Valeur
0       Afghanistan   2013  Autres non-céréales    682000
1       Afghanistan   2014  Autres non-céréales    335000
2       Afghanistan   2013         Blé et Farin  39224000
3       Afghanistan   2014         Blé et Farin  15160000
4       Afghanistan   2013             Céréales  40504000

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">2.3 - Analyse exploratoire du fichier sous nutrition</h3>
</div>

In [100]:
#Afficher les dimensions du dataset
sous_nutrition.shape

(1218, 3)

In [101]:
#Consulter le nombre de colonnes
sous_nutrition.shape[1]

3

In [102]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

In [110]:
#Conversion de la colonne sous nutrition en numérique
sous_nutrition.dtypes
sous_nutrition[sous_nutrition['Valeur'] == "<0.1"]
#sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'])

         Zone      Année Valeur
60    Arménie  2012-2014   <0.1
61    Arménie  2013-2015   <0.1
62    Arménie  2014-2016   <0.1
63    Arménie  2015-2017   <0.1
64    Arménie  2016-2018   <0.1
...       ...        ...    ...
1183  Vanuatu  2013-2015   <0.1
1184  Vanuatu  2014-2016   <0.1
1185  Vanuatu  2015-2017   <0.1
1186  Vanuatu  2016-2018   <0.1
1187  Vanuatu  2017-2019   <0.1

[120 rows x 3 columns]

In [117]:
#Conversion de la colonne (avec l'argument errors=coerce qui permet de convertir automatiquement les lignes qui ne sont pas des nombres en NaN)
#Puis remplacement des NaN en 0
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'], errors="coerce")
sous_nutrition = sous_nutrition.fillna(0)

In [125]:
#changement du nom de la colonne Valeur par sous_nutrition
sous_nutrition.rename(columns = {'Valeur': 'sous_nutrition'}, inplace= "True" )

In [127]:
#Multiplication de la colonne sous_nutrition par 1000000
sous_nutrition["sous_nutrition"] *= 1000000

In [128]:
#Afficher les 5 premières lignes de la table
sous_nutrition.head()

          Zone      Année  sous_nutrition
0  Afghanistan  2012-2014       8600000.0
1  Afghanistan  2013-2015       8800000.0
2  Afghanistan  2014-2016       8900000.0
3  Afghanistan  2015-2017       9700000.0
4  Afghanistan  2016-2018      10500000.0

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.1 - Proportion de personnes en sous nutrition</h3>
</div>

In [160]:
# Il faut tout d'abord faire une jointure entre la table population et la table sous nutrition, en ciblant l'année 2017
population[population["Année"] == 2017]

# different values of Année in sous_nutrition
#sous_nutrition.groupby("Année")["sous_nutrition"].mean()

# sous_nutrition 2015-2017 | 2017-2019
sous_nutrition[(sous_nutrition["Année"] == "2015-2017") | (sous_nutrition["Année"] == "2017-2019")]

# sous_nutrition 2015-2017 | 2017-2019 -> Moyenne lorsque double représentation
sous_nut_2017 = sous_nutrition[(sous_nutrition["Année"] == "2015-2017") | (sous_nutrition["Année"] == "2017-2019")].groupby("Zone")["sous_nutrition"].mean()
#display(sous_nut_2017)


Pop_SsNut_2017 = population[population["Année"] == 2017].merge(sous_nut_2017, on = "Zone")

In [174]:
#Affichage du dataset
Pop_SsNut_2017.sort_values(by = "sous_nutrition", ascending = False)

           Zone  Année    Population  sous_nutrition
84         Inde   2017  1.338677e+09     190050000.0
136    Pakistan   2017  2.079062e+08      25350000.0
85    Indonésie   2017  2.646510e+08      24050000.0
128     Nigéria   2017  1.908732e+08      23400000.0
16   Bangladesh   2017  1.596854e+08      21600000.0
..          ...    ...           ...             ...
196     Uruguay   2017  3.436641e+06             0.0
197     Vanuatu   2017  2.855100e+05             0.0
200       Yémen   2017  2.783482e+07             0.0
201      Zambie   2017  1.685360e+07             0.0
202    Zimbabwe   2017  1.423660e+07             0.0

[203 rows x 4 columns]

In [180]:
#Calcul et affichage du nombre de personnes en état de sous nutrition

print("Nombre total de personnes en sous nutrition en 20217")
print(Pop_SsNut_2017["sous_nutrition"].sum())

print("Nombre total de personnes dans les données")
print(Pop_SsNut_2017["Population"].sum())

print("Proportion de personnes en sous-nutrition")
print("{:.2%}".format(Pop_SsNut_2017["sous_nutrition"].sum() / Pop_SsNut_2017["Population"].sum()))

Nombre total de personnes en sous nutrition en 20217
536400000.0
Nombre total de personnes dans les données
7543798779.0
Proportion de personnes en sous-nutrition
7.11%

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.2 - Nombre théorique de personne qui pourrait être nourries</h3>
</div>

In [103]:
#Combien mange en moyenne un être humain ? Source =>

In [104]:
#On commence par faire une jointure entre le data frame population et Dispo_alimentaire afin d'ajouter dans ce dernier la population

In [105]:
#Affichage du nouveau dataframe

In [106]:
#Création de la colonne dispo_kcal avec calcul des kcal disponibles mondialement

In [107]:
#Calcul du nombre d'humains pouvant être nourris

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.3 - Nombre théorique de personne qui pourrait être nourrie avec les produits végétaux</h3>
</div>

In [108]:
#Transfert des données avec les végétaux dans un nouveau dataframe

In [109]:
#Calcul du nombre de kcal disponible pour les végétaux

In [110]:
#Calcul du nombre d'humains pouvant être nourris avec les végétaux

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.4 - Utilisation de la disponibilité intérieure</h3>
</div>

In [111]:
#Calcul de la disponibilité totale

In [112]:
#création d'une boucle for pour afficher les différentes valeurs en fonction des colonnes aliments pour animaux, pertes, nourritures,

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.5 - Utilisation des céréales</h3>
</div>

In [113]:
#Création d'une liste avec toutes les variables

In [114]:
#Création d'un dataframe avec les informations uniquement pour ces céréales

In [115]:
#Affichage de la proportion d'alimentation animale

In [116]:
#Affichage de la proportion d'alimentation animale

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.6 - Pays avec la proportion de personnes sous-alimentée la plus forte en 2017</h3>
</div>

In [117]:
#Création de la colonne proportion par pays

In [118]:
#affichage après trie des 10 pires pays

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.7 - Pays qui ont le plus bénéficié d'aide alimentaire depuis 2013</h3>
</div>

In [119]:
#calcul du total de l'aide alimentaire par pays

In [120]:
#affichage après trie des 10 pays qui ont bénéficié le plus de l'aide alimentaire

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.8 - Evolution des 5 pays qui ont le plus bénéficiés de l'aide alimentaire entre 2013 et 2016</h3>
</div>

In [121]:
#Création d'un dataframe avec la zone, l'année et l'aide alimentaire puis groupby sur zone et année

In [122]:
#Création d'une liste contenant les 5 pays qui ont le plus bénéficiées de l'aide alimentaire

In [123]:
#On filtre sur le dataframe avec notre liste

In [124]:
# Affichage des pays avec l'aide alimentaire par année

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.9 - Pays avec le moins de disponibilité par habitant</h3>
</div>

In [125]:
#Calcul de la disponibilité en kcal par personne par jour par pays

In [126]:
#Affichage des 10 pays qui ont le moins de dispo alimentaire par personne

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.10 - Pays avec le plus de disponibilité par habitant</h3>
</div>

In [127]:
#Affichage des 10 pays qui ont le plus de dispo alimentaire par personne

<div style="border: 1px solid RGB(0,150,250);" >
<h3 style="margin: auto; padding: 20px; color: RGB(0,150,250); ">3.11 - Exemple de la Thaïlande pour le Manioc</h3>
</div>

In [128]:
#création d'un dataframe avec uniquement la Thaïlande

In [129]:
#Calcul de la sous nutrition en Thaïlande

In [130]:
# On calcule la proportion exportée en fonction de la proportion

<div style="background-color: RGB(0,150,250);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 6 - Analyse complémentaires</h2>
</div>

In [131]:
#Rajouter en dessous toutes les analyses complémtaires suite à la demande de mélanie :
#"et toutes les infos que tu trouverais utiles pour mettre en relief les pays qui semblent être 
#le plus en difficulté au niveau alimentaire"